midf/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from core.views import LoginView
from core.views import DashboardView
from core.views import ProximamenteView
from core.views.login import LogoutView
from core.views.reservoir import ReservoirView
from core.views.project import ProjectListView, ProjectFormView, DeleteProjectView
from core.views.simulation import InitialConditionsFormView, SimulationConditionsFormView
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()
lr = login_required

urlpatterns = patterns('',
    url(r'^$', lr(DashboardView.as_view()), name='dashboard'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(url='/login'), name='logout'),
    url(r'^dashboard/$', lr(DashboardView.as_view()), name='dashboard'),
    url(r'^projects/$', lr(ProjectListView.as_view()), name='project_list'),
    url(r'^projects/add/$', lr(ProjectFormView.as_view()), name='add_project'),
    url(r'^projects/(?P<project_id>[0-9])/edit/$', lr(ProjectFormView.as_view()), name='edit_project'),
    url(r'^projects/(?P<project_id>[0-9])/delete/$', lr(DeleteProjectView.as_view()), name='delete_project'),
    url(r'^proximamente/$', ProximamenteView.as_view(), name='proximamente'),
    url(r'^reservoir/add$', lr(ReservoirView.as_view()), name='add_reservoir'),
    url(r'^reservoir/(?P<reservoir_id>[0-9])/edit/$', lr(ReservoirView.as_view()), name='edit_reservoir'),

    url(r'^initial_conditions/add$',lr(InitialConditionsFormView.as_view()), name='add_initialcond'),
    url(r'^initialcond/(?P<initialcond_id>[0-9])/edit/$', lr(InitialConditionsFormView.as_view()), name='edit_initialcond'),

    url(r'^simulation_conditions/add$',lr(SimulationConditionsFormView.as_view()), name='add_simulationcond'),
    url(r'^simulationcond/(?P<simulationcond_id>[0-9])/edit/$', lr(SimulationConditionsFormView.as_view()), name='edit_simulationcond'),

    # Examples:
    # url(r'^$', 'midf.views.home', name='home'),
    # url(r'^midf/', include('midf.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/forms/login.py
from django.contrib.auth.forms import AuthenticationForm
from django import forms
import re


class LoginForm(AuthenticationForm):
    pat_reg = re.compile('^[a-zA-Z0-9_]+$')

    def clean_username(self):
        username = self.cleaned_data['username']

        if self.validate_special_chars(username):
            return username

    def clean_password(self):
        password = self.cleaned_data['password']
        if self.validate_special_chars(password):
            return password

    def validate_special_chars(self, value):
        if not self.pat_reg.match(value):
            raise forms.ValidationError(
                "Este campo no puede contener caracteres especiales #$%&/..., etc.")

        return True

core/forms/project.py
from django import forms
from core.models import Project

EMPTY_CHOICE = ('', '-----')
OPT_NONE, OPT_EQUALS, OPT_CONTAINS = '','1', '2'

class ProjectForm(forms.ModelForm):

    class Meta:
        model = Project


class ProjectSearchForm(forms.Form):
    name_filter =  forms.ChoiceField(choices=(EMPTY_CHOICE, (OPT_EQUALS,'Equals'), (OPT_CONTAINS, 'Contains')), required=False)
    name_value =  forms.CharField(required=False)

    date_from = forms.DateField(required=False)
    date_to = forms.DateField(required=False)
    description_filter =  forms.ChoiceField(choices=(EMPTY_CHOICE, (OPT_CONTAINS,'Contains')), required=False)
    description_value = forms.CharField(required=False, max_length=100, label='Description')


    def get_projects(self):
        project_basequeryset = Project.objects.all()
        if not self.is_bound: # form hasn't been delivered yet
            return project_basequeryset
        if self.is_valid():
            #Filter data
            pname_filter  = self.cleaned_data['name_filter']
            pname_value = self.cleaned_data['name_value']
            description_filter  = self.cleaned_data['description_filter']
            description_value = self.cleaned_data['description_value']
            date_from = self.cleaned_data['date_from']
            date_to = self.cleaned_data['date_to']

            # Filter queryset
            project_qset = project_basequeryset # Base query

            # Filter by project name
            #pdb.set_trace()
            if pname_filter == OPT_EQUALS:
                project_qset = project_qset.filter(name=pname_value)
            elif pname_filter == OPT_CONTAINS:
                project_qset = project_qset.filter(name__contains=pname_value)

            # Filter by  description
            if description_filter == OPT_EQUALS:
                project_qset = project_qset.filter(description=description_value)
            elif description_filter == OPT_CONTAINS:
                project_qset = project_qset.filter(description__contains=description_value)
            #Filter by date
            if date_from is not None and date_to is not  None:
                project_qset = project_qset.filter(date__range=[date_from, date_to])
            elif date_from is not None:
                project_qset = project_qset.filter(date__gt=date_from) #greater than
            elif date_to is not None:
                project_qset = project_qset.filter(date__lt=date_to) #less than

            return project_qset
        else:
            return Project.objects.none()
        return project_basequeryset
        

    '''Validators'''

    def clean_name_value(self):
        value = self.cleaned_data['name_value']
        selected_filter  = self.cleaned_data['name_filter']

        if selected_filter != OPT_NONE and value.strip() == '':
            raise forms.ValidationError(" Please input value for selected name filter")
        elif selected_filter == OPT_NONE and value.strip() != '':
            raise forms.ValidationError(" Please select a filter type for name value")
        return value

    def clean_description_value(self):
        value = self.cleaned_data['description_value']
        selected_filter  = self.cleaned_data['description_filter']

        if selected_filter != OPT_NONE and value.strip() == '':
            raise forms.ValidationError(" Please input value for selected description filter")
        elif selected_filter == OPT_NONE and value.strip() != '':
            raise forms.ValidationError(" Please select a filter type for description value")
        return value

    def clean_date_to(self):
        date_from = self.cleaned_data['date_from']
        date_to = self.cleaned_data['date_to']
        if date_from is None and date_to is None:
            return None

        if date_from is not None and date_to is not None:
            if date_to < date_from:
                raise forms.ValidationError(" Date interval error (to < from)")

        return date_to

core/forms/reservoir.py
from django import forms
from core.models import Reservoir

class ReservoirForm(forms.ModelForm):
    
    class Meta:
        model = Reservoir

core/forms/simulation.py
from django import forms
from core.models import Simulation, SimulationConditions, InitialConditions


class SimulationForm(forms.ModelForm):

    class Meta:
        fields = ('name', )
        model = Simulation


class SimulationConditionsForm(forms.ModelForm):

    class Meta:
        model = SimulationConditions
        exclude = ('simulation',)


class InitialConditionsForm(forms.ModelForm):

    class Meta:
        model = InitialConditions
        exclude = ('simulation',)

core/views/base.py
from django.views.generic.edit import UpdateView, ModelFormMixin, ProcessFormView
from django.views.generic.detail import SingleObjectTemplateResponseMixin
from django.core.urlresolvers import reverse
from django.http.response import HttpResponseRedirect
from core.models import Reservoir, Project, Simulation
from django.contrib import messages 
from core import messages as msg

class BaseModelFormView(UpdateView):

    def get_object(self, queryset=None):
        if self.pk_url_kwarg in self.kwargs: # Edit
            return super(BaseModelFormView, self).get_object(queryset=queryset)
        else: # Add
            return None

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(BaseModelFormView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super(BaseModelFormView, self).post(request, *args, **kwargs)

    def form_valid(self, form, get_args=''):
        super(BaseModelFormView, self).form_valid(form)
        self.success_url = reverse(self.success_url, kwargs={self.pk_url_kwarg: self.object.pk}) + '?' + get_args
        messages.add_message(self.request, messages.SUCCESS, msg.FORM_SUCCESS)
        return HttpResponseRedirect(self.get_success_url())
    
    def form_invalid(self, form, get_args=''):
        messages.add_message(self.request, messages.ERROR, msg.FORM_ERROR)

        return super(BaseModelFormView, self).form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super(BaseModelFormView, self).get_context_data(**kwargs)
        if self.object is None:
            context['mode'] = 'create'
        else:
            context['mode'] = 'update'
        return context


class BaseSimulationStepFormView(BaseModelFormView):
    simulation = None

    def form_valid(self, form):
        if 'sim_id' in self.request.GET:
            sim_id = self.request.GET['sim_id']
            response = super(BaseSimulationStepFormView, self).form_valid(form, 'sim_id=%s'%(sim_id)) # Add sim_id to preserve simulation context
            self.simulation = Simulation.objects.get(pk=sim_id)
        else:
            response = super(BaseSimulationStepFormView, self).form_valid(form)
        return response
    
    def get_context_data(self, **kwargs):
        context = super(BaseSimulationStepFormView, self).get_context_data(**kwargs)
        # Add relevant instances to template context
        if 'sim_id' in self.request.GET:
            simulation = Simulation.objects.get(pk=self.request.GET['sim_id'])
            project = simulation.project
            context['simulation'] = simulation
            context['project'] = project
        return context

core/views/dashboard.py
from django.views.generic import TemplateView


class DashboardView(TemplateView):
    template_name = 'dashboard.html'

core/views/login.py
from django.views.generic.edit import FormView
from django.views.generic import TemplateView, RedirectView
from core.forms.login import LoginForm
from django.contrib.auth import login, logout
       

class LoginView(FormView):

    template_name = 'login.html'
    form_class = LoginForm
    success_url = '/dashboard/'

    def form_valid(self, form):
        user = form.user_cache
        login(self.request, user)
        return super(LoginView, self).form_valid(form)

class LogoutView(RedirectView):

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return super(LogoutView, self).dispatch(*args, **kwargs)

core/views/project.py
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import FormView
from core.models import Project, Simulation
from core.forms.project import ProjectForm
from core.views.base import BaseModelFormView
from core.forms.project import ProjectSearchForm
from django.contrib import messages 
from core import messages as msg


class ProjectListView(ListView):
    template_name = 'project_list.html'
    model = Project # TODO filter projects owned by user only?

    
    def dispatch(self, *args, **kwargs):
        self.search_form = ProjectSearchForm(self.request.POST or None)
        return super(ProjectListView, self).dispatch(*args, **kwargs)
    
    def post(self, request):
        return super(ProjectListView, self).get(request)

    def get_queryset(self):
        return self.search_form.get_projects()

    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context['search_form'] = self.search_form
        return context


class ProjectFormView(BaseModelFormView):
    template_name = 'project_form.html'
    success_url = 'edit_project'
    form_class = ProjectForm
    model = Project
    pk_url_kwarg = 'project_id'
    context_object_name = 'project'

    def form_valid(self, form):
        response = super(ProjectFormView, self).form_valid(form)
        # self.object is created inside super.form_valid
        project = self.object
        # Create default simulation only if project doesn't have one
        project.create_base_simulation()
        return response

    def get_context_data(self, **kwargs):
        context = super(ProjectFormView, self).get_context_data(**kwargs)
        if self.object is not None:
            # Reference simulation if project exists
            context['simulation'] = self.object.simulation_set.all()[0]
        return context


class DeleteProjectView(TemplateView):
    template_name = 'project_delete.html'
    
    def get(self, request, *args, **kwargs):
        project_id = self.kwargs['project_id']
        project = Project.objects.get(pk=project_id)
        project.delete()
        print "deleted"
        messages.add_message(self.request, messages.SUCCESS, msg.PROJECT_DELETE)
        return super(DeleteProjectView, self).get(request)

core/views/proximamente.py
from django.views.generic import TemplateView
       

class ProximamenteView(TemplateView):

    template_name = 'proximamente.html'
    

core/views/reservoir.py
from django.views.generic.edit import FormView
from core.forms.reservoir import ReservoirForm
from core.views.base import BaseSimulationStepFormView
from core.models import Reservoir, Project, Simulation

class ReservoirView(BaseSimulationStepFormView):
    template_name = 'reservoir.html'
    success_url = 'edit_reservoir'
    form_class = ReservoirForm
    model = Reservoir
    pk_url_kwarg = 'reservoir_id'
    context_object_name = 'reservoir'
    
    def form_valid(self, form):
        response = super(ReservoirView, self).form_valid(form)
        if 'sim_id' in self.request.GET:
            #Add reservoir to simulation
            self.simulation.reservoir = self.object
            self.simulation.save()
        return response

core/views/simulation.py
from django.views.generic.edit import FormView
from core.forms.simulation import (
    SimulationForm, SimulationConditionsForm, InitialConditionsForm)
from core.views.base import BaseSimulationStepFormView
from core.models import InitialConditions, SimulationConditions

class SimulationFormView(FormView):
    template_name = ''
    form_class = SimulationForm
    success_url = ''

    def form_valid(self, form):
        form.save(commit=True)
        return super(SimulationFormView, self).form_valid(form)


class SimulationConditionsFormView(BaseSimulationStepFormView):
    template_name = 'simulation_conditions_form.html'
    form_class = SimulationConditionsForm
    success_url = 'edit_simulationcond'
    model = SimulationConditions
    pk_url_kwarg = 'simulationcond_id'
    context_object_name = 'simulationcond'

    def form_valid(self, form):
        response = super(SimulationConditionsFormView, self).form_valid(form)
        if 'sim_id' in self.request.GET:
            # Add simulationconds to simulation
            self.simulation.simulation_conditions = self.object
            self.simulation.save()
        self.object.save()
        return response


class InitialConditionsFormView(BaseSimulationStepFormView):
    template_name = 'initial_conditions_form.html'
    success_url = 'edit_initialcond'
    form_class = InitialConditionsForm
    model = InitialConditions
    pk_url_kwarg = 'initialcond_id'
    context_object_name = 'initialcond'

    def form_valid(self, form):
        response = super(InitialConditionsFormView, self).form_valid(form)
        if 'sim_id' in self.request.GET:
            # Add initialconds to simulation
            self.simulation.initial_conditions = self.object
            self.simulation.save()
        self.object.save()
        return response

core/templates/base_layout.html
{% load staticfiles %}

<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <title>{%block title%}MIDF{%endblock%}</title>
  <meta name="viewport" content="width=device-width">

  {% block meta %}
  {% endblock %}
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css">
 
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-flatty.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  
  {% block css %}{% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="http://code.jquery.com/ui/1.11.0/jquery-ui.min.js"></script>
  {% block js %}{% endblock %}

  <script>
    $(document).ready(
            function() {
                {% block jquery %}{% endblock %}
            }
  );
  </script>
  </head>

<body class="{% block body_class %}{% endblock %}">
{% block body %}
  <header>
    {% block header %}
    <div id="main_menu">
        <div class='navbar'>
            <div class="container navbar-inner">
                
                    <div id='logo' class="navbar-header">
                        <span  class="navbar-brand">MIDF</span>
                    </div>

                    <div class=''>
                        <div class="user_ico">
                            User: <b>Juan Perez</b><br/> 
                            <a href='{%url 'dashboard'%}'>Home</a> | <a href='/login' id='logout_link'>Logout</a>
                        </div>
                    </div>
              </div>
          </div>
  </div>
       
    {% endblock %}
  </header>

  <div class='main-body container' role="main">
    {%block navigation%}{% endblock %} 
    {% block content %}{% endblock %}
  </div>

  <footer>
    {% block footer %}
    <div class="footer_container">
        +Contactos varios <br/>
        +Patrocinadores
    </div>

    {% endblock footer %}
  </footer>
{% endblock %}
</body>
</html>

core/templates/dashboard.html
{% extends "base_layout.html" %}
{%load staticfiles%}
{%block css%}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{%endblock%}

{%block content%}


<div  id="icon_cont">
	<ul class="icon_list" id="icon_ul">
		<li>
        <a href="{%url 'project_list'%}" id='project_link'>
			<i class="fa fa-cubes fa-5x"></i>
            <span>Projects</span>
			</a>
		</li>
		<li>
			<a href="http://localhost:8000/proximamente">
			<i class="fa fa-bar-chart-o fa-5x"  id='simulation_link'></i>
            <span>Simulation</span>
			</a>
		</li>
        <li>
            <a href="/proximamente" id='field_link'>
                <i class="fa fa-globe fa-5x"></i>
                <span>Fields and Wells</span>
			</a>
		</li>

        <li>
			<a href="http://localhost:8000/proximamente"  id='settings_link'>
			<i class="fa fa-gears fa-5x"></i>
            <span>Settings</span>
			</a>
		</li>


		<li>
			<a href="http://localhost:8000/proximamente"  id='parameters_link'>
			<i class="fa fa-list fa-5x" ></i>
            <span>Parameters and units</span>
			</a>
		</li>
		<li>
			<a href="http://localhost:8000/proximamente">
			<i class="fa fa-book fa-5x"  id='help_link'></i>
            <span>Help</span>
			</a>
		</li>
       
	</ul>
</div>

{%endblock%}

{%block js%}
<script src="{%static 'js/forms.js'%}"></script>
{%endblock%}

{%block jquery%}
{%endblock%}

core/templates/datainput_sidebar.html
<div class='sidebar-cont info'>
    <ul class='sidebar'>
        <li><a href='{%if project%}{%url 'edit_project' project_id=project.pk%}{%else%}{%url 'add_project'%}{%endif%}'>General</a></li>
        {%if project%}
            <li><a href='{%if simulation.reservoir%}
                {%url 'edit_reservoir' reservoir_id=simulation.reservoir.pk%}?sim_id={{simulation.pk}}
                {%else%}
                    {%url 'add_reservoir'%}?sim_id={{simulation.pk}}
                {%endif%}'>Reservoir</a></li>
            
            <li><a  href='{%if simulation.get_initial_conditions%}
                {%url 'edit_initialcond' initialcond_id=simulation.get_initial_conditions.pk%}?sim_id={{simulation.pk}}
                {%else%}
                {%url 'add_initialcond'%}?sim_id={{simulation.pk}}
                {%endif%}'>Initial conditions</a></li>


            <li><a  class='disabled'>PVT properties</a></li>
            <li><a  class='disabled'>KRS</a></li>
            <li>
                <a id='optional_btn' href='#'>Optional</a>
                <ul id='optional_menu'>
                    <li><a  href='{%if simulation.get_simulation_conditions%}
                    {%url 'edit_simulationcond' simulationcond_id=simulation.get_simulation_conditions.pk%}?sim_id={{simulation.pk}}
                    {%else%}
                    {%url 'add_simulationcond'%}?sim_id={{simulation.pk}}
                    {%endif%}'>Simulation conditions</a></li>
                </ul>
            </li>
        {%else%}
             <li><a class='disabled'>Reservoir</a></li>
            <li><a  class='disabled'>Initial conditions</a></li>
            <li><a  class='disabled'>PVT properties</a></li>
            <li><a  class='disabled'>KRS</a></li>
            <li>Optional</li>
        {%endif%}
    </ul>
</div>

<script>
$(document).ready(function(){
        
        //Hide optional menu
        $("#optional_menu").hide();

        $(".sidebar [href]").each(function() {
            if (this.href == window.location.href) {
                $(this).addClass("active");
                //Show optional menu if necesary
                if($(this).parent().parent().attr('id')== "optional_menu") {
                    $("#optional_menu").show();
                } 
                
                }
            });
        
        
        $("#optional_btn").click(function () {$("#optional_menu").show(400);});
        });
</script>

core/templates/initial_conditions_form.html
{% extends "project_form_step.html" %}
{%load staticfiles%}
{%block form_title%}Initial Conditions <b>(3/5)</b>{%endblock%}
{%block form_class%}initial-conditions-form{%endblock%}

core/templates/login.html
{% extends "base_layout.html" %}
{%load staticfiles%}
{%block css%}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{%endblock%}
{%block header%}

{%block footer%}
{%endblock%}

{%endblock%}
{%block content%}
<div id='login_container' class="container">

    <div class="col-md-4 col-md-offset-4">
        {% if form.errors %}
        <div class="alert alert-danger">
            <b>Error:</b> {{ form.errors }}
        </div>

        {% endif %}

        <div class="panel panel-default">
            <div class="panel-heading"><h3 class="panel-title"><strong>MIDF - Start Session</strong></h3></div>
            <div class="panel-body">
                <form role="form" method='POST' id='login_form'>
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="{{ form.username.id_for_label }}">Username</label>
                        {{ form.username }}
                    </div>
                    <div class="form-group">
                        <label for=" {{ form.password.id_for_label }} ">Password</label>
                        {{ form.password }}
                    </div>
                    <button id='submit_login' type="submit" class="btn btn-sm btn-default">Start Session</button>
                    <button id='clean_login' type="button" class="btn btn-sm btn-default">Reset</button>
                </form>
            </div>
        </div>
    </div>
</div>

{%endblock%}

{%block js%}
<script src="{%static 'js/forms.js'%}"></script>
{%endblock%}

{%block jquery%}
$('#clean_login').click(
function() {
    clean_fields('login_form');
});
{%endblock%}

core/templates/project_delete.html
{% extends "base_layout.html" %}
{%block header%}
{%endblock%}
{%block jquery%}
window.location.href='/projects/';
{%endblock%}
{%block footer%}
{%endblock%}

core/templates/project_form.html
{% extends "project_form_step.html" %}
{%load staticfiles%}
{%block form_title%}Project General Information <b>(1/5)</b>{%endblock%}
{%block prevnext_btns%}
    {%if project%}
        {#Show next prev only if project was saved#}
        {{block.super}}
    {%endif%}
{%endblock%}

core/templates/project_list.html
{% extends "base_layout.html" %}
{%load staticfiles%}
{%block navigation%}<a href='/'>Home</a> &raquo; Projects{% endblock %} 
{%block css%}
<link rel="stylesheet" href="{% static 'css/dashboard.css' %}">
{%endblock%}

{%block content%}

<div class='row'>
    <div class='col-md-12'>
        <h1>Projects</h1>
        {%for message in messages%}
        <div class='alert alert-success'>{{message}}</div>
        {%endfor%}
        <a class='btn btn-info' href='{%url "add_project"%}'>New project</a>
        <br/>
        {%include "project_search_form.html"%}
        <br/>
        {%if object_list%}
        <table class='table table-bordered table-hover table-condensed'>
            <thead>
                <tr>
                    <th>Project</th>
                    <th>Description</th>
                    <th>Date</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
            {%for project in object_list%}
            <tr>

                    <td>
                    <a href='{%url "edit_project" project_id=project.pk%}'>{{project}}</a>
                    </td>
                    <td>{{project.description}}</td>
                    <td>{{project.date}}</td>
                    <td>
                        Copy | 
                        <a class='delete_btn' href='{%url 'delete_project' project_id=project.pk%}'>Delete</a>
                    </td>
            </tr>
        {%endfor%}
        </tbody>
    </table>
        {%else%}
        <h4>No projects found.</h4>
        {%endif%}
    </div>
</div>

{%endblock%}

{%block js%}
<script src="{%static 'js/forms.js'%}"></script>
{%endblock%}

{%block jquery%}
    $(".delete_btn").click(
        function(){
            if (confirm('Are you sure you want to delete this project?')) {
                return true;
            } else {
                // Do nothing!
                return false;
            }
            
        }
    );
{%endblock%}

{% block footer %}
{% endblock footer %}

core/templates/project_search_form.html
<div id='project_search_form' class='panel panel-default'>
    <div class='panel-heading'> <h3 >Search filters</h3> </div>
    <form method='POST'>
        {% csrf_token %}
        {%if search_form.errors%}
        <div class='alert alert-danger'>Errors: <br/>{{search_form.errors}}</div>
        {%endif%}
                <div>
                    <label>Project</label>
                    {{search_form.name_filter}}
                    {{search_form.name_value}}
                </div>

                <div class='date_inputs'>
                    <label>Date</label>
                    From: {{search_form.date_from}}
                    To: {{search_form.date_to}}
                </div>

                <div>
                    <label>Description</label>
                    {{search_form.description_filter}}
                    {{search_form.description_value}}
                </div>

                <div class='disabled'>
                    <label>Simulation type</label>
                    <select disabled>
                        <option>Damage discretization</option>
                        <option>Remediation</option>
                    </select>
                </div>
                
                <div class='disabled'>
                    <label>Module</label>
                    <select disabled>
                        <optgroup label='Damage'>
                            <option>Module 1</option>
                            <option>Module 2</option>
                        </optgroup>
                        <optgroup label='Remediation'>
                            <option>Module 3</option>
                            <option>Module 4</option>
                        </optgroup>

                    </select>
                </div>

                <center><button id='clean_btn' type='button' class='btn btn-default'> Clean</button>&nbsp;<button id='submit_btn' type='submit' class='btn btn-default'> Filter</button></center>
    </form>
</div>


<script>
  $(function() {
    $( "#id_date_from" ).datepicker();
    $( "#id_date_to" ).datepicker();
    /*TODO move to proper js scripts*/
    $('#clean_btn').click(
    function() {
        $(this).closest('form').find("input[type=text], textarea").val("");
        $(this).closest('form').find("select").prop('selectedIndex',0);
    });
  });
</script>

core/templates/proximamente.html
{% extends "base_layout.html" %}
{%load staticfiles%}
{%block css%}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{%endblock%}

{%block content%}
Proximamente!
{%endblock%}

{%block js%}
<script src="{%static 'js/forms.js'%}"></script>
{%endblock%}

{%block jquery%}
$('#clean_login').click(
function() {
    clean_fields('login_form');
});
{%endblock%}

core/templates/reservoir.html
{% extends "project_form_step.html" %}
{%load staticfiles%}
{%block form_title%}Reservoir Information <b>(2/5)</b>{%endblock%}
{%block form_class%}reservoir-form{%endblock%}